using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace BikeShop.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 3/21/2017 11:54:05 PM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// BikeShop Domain objects

    public partial class Vendor : Entity<Vendor>
	{
		public Vendor() { }
		public Vendor(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string AccountNumber { get; set; }
        public string Name { get; set; }
    }
}
